[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# debug probe
#runner = "probe-rs run --chip RP2040"

# USB flash
runner = "elf2uf2-rs --deploy --serial --verbose"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
